syntax = "proto3";

package api_user;

option go_package = "gochat/api/api/user";

import "validate/validate.proto";
import "google/api/annotations.proto";

// API端用户服务
service ApiUser {
  // 用户注册
  rpc Register(RegisterRequest) returns (RegisterResponse) {
    option(google.api.http) = {
      post:"/api/user/register"
      body:"*"
    };
  };
  
  // 用户登录
  rpc Login(LoginRequest) returns (LoginResponse) {
    option(google.api.http) = {
      post:"/api/login"
      body:"*"
    };
  };
  
  // 获取用户信息
  rpc GetUserInfo(GetUserInfoRequest) returns (GetUserInfoResponse) {
    option(google.api.http) = {
      get:"/api/user/info"
    };
  };
}

// 用户注册请求
message RegisterRequest {
  // @inject_tag: json:"name"
  string name = 1[(validate.rules).string.min_len = 1];
  // @inject_tag: json:"password"
  string password = 2[(validate.rules).string.min_len = 6];
  // @inject_tag: json:"phone"
  string phone = 3;
  // @inject_tag: json:"email"
  string email = 4;
  // @inject_tag: json:"client_ip"
  string client_ip = 5;
  // @inject_tag: json:"client_port"
  string client_port = 6;
  // @inject_tag: json:"device_info"
  string device_info = 7;
}

// 用户注册响应
message RegisterResponse {
  int32 code = 1;
  string message = 2;
  UserInfo data = 3;
}

// 登录请求
message LoginRequest {
  // @inject_tag: json:"name"
  string name = 1[(validate.rules).string.min_len = 1];
  // @inject_tag: json:"password"
  string password = 2[(validate.rules).string.min_len = 1];
}

// 登录响应
message LoginResponse {
  string message = 1;
  UserInfo data = 2;
  string token = 3;
  int64 expire = 4;
}

// 获取用户信息请求
message GetUserInfoRequest {
  // @inject_tag: form:"id"
  int64 id = 1[(validate.rules).int64.gt = 0];
}

// 获取用户信息响应
message GetUserInfoResponse {
  string message = 1;
  UserInfo user = 2;
}

// 用户信息
message UserInfo {
  int64 id = 1;
  string name = 2;
  string phone = 3;
  string email = 4;
  string avatar = 5;
  string client_ip = 6;
  string client_port = 7;
  int64 login_time = 8;
  string identity = 9;
  int64 heart_time = 10;
  int64 logout_time = 11;
  string device_info = 12;
  string created_at = 13;
  string updated_at = 14;
}
