// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/group/group.proto

package group

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GroupInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GroupInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GroupInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GroupInfoMultiError, or nil
// if none found.
func (m *GroupInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *GroupInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Avatar

	// no validation rules for OwnerId

	// no validation rules for Notice

	// no validation rules for MemberCount

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GroupInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GroupInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GroupInfoValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GroupInfoValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GroupInfoValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GroupInfoValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GroupInfoMultiError(errors)
	}

	return nil
}

// GroupInfoMultiError is an error wrapping multiple validation errors returned
// by GroupInfo.ValidateAll() if the designated constraints aren't met.
type GroupInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GroupInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GroupInfoMultiError) AllErrors() []error { return m }

// GroupInfoValidationError is the validation error returned by
// GroupInfo.Validate if the designated constraints aren't met.
type GroupInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GroupInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GroupInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GroupInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GroupInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GroupInfoValidationError) ErrorName() string { return "GroupInfoValidationError" }

// Error satisfies the builtin error interface
func (e GroupInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGroupInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GroupInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GroupInfoValidationError{}

// Validate checks the field values on GroupMemberInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GroupMemberInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GroupMemberInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GroupMemberInfoMultiError, or nil if none found.
func (m *GroupMemberInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *GroupMemberInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for GroupId

	// no validation rules for UserId

	// no validation rules for Role

	// no validation rules for Nickname

	// no validation rules for UserName

	// no validation rules for UserAvatar

	// no validation rules for UserPhone

	// no validation rules for IsOnline

	if all {
		switch v := interface{}(m.GetJoinedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GroupMemberInfoValidationError{
					field:  "JoinedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GroupMemberInfoValidationError{
					field:  "JoinedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetJoinedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GroupMemberInfoValidationError{
				field:  "JoinedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GroupMemberInfoMultiError(errors)
	}

	return nil
}

// GroupMemberInfoMultiError is an error wrapping multiple validation errors
// returned by GroupMemberInfo.ValidateAll() if the designated constraints
// aren't met.
type GroupMemberInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GroupMemberInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GroupMemberInfoMultiError) AllErrors() []error { return m }

// GroupMemberInfoValidationError is the validation error returned by
// GroupMemberInfo.Validate if the designated constraints aren't met.
type GroupMemberInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GroupMemberInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GroupMemberInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GroupMemberInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GroupMemberInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GroupMemberInfoValidationError) ErrorName() string { return "GroupMemberInfoValidationError" }

// Error satisfies the builtin error interface
func (e GroupMemberInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGroupMemberInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GroupMemberInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GroupMemberInfoValidationError{}

// Validate checks the field values on CreateGroupRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateGroupRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateGroupRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateGroupRequestMultiError, or nil if none found.
func (m *CreateGroupRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateGroupRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Avatar

	if len(errors) > 0 {
		return CreateGroupRequestMultiError(errors)
	}

	return nil
}

// CreateGroupRequestMultiError is an error wrapping multiple validation errors
// returned by CreateGroupRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateGroupRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateGroupRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateGroupRequestMultiError) AllErrors() []error { return m }

// CreateGroupRequestValidationError is the validation error returned by
// CreateGroupRequest.Validate if the designated constraints aren't met.
type CreateGroupRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateGroupRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateGroupRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateGroupRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateGroupRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateGroupRequestValidationError) ErrorName() string {
	return "CreateGroupRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateGroupRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateGroupRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateGroupRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateGroupRequestValidationError{}

// Validate checks the field values on CreateGroupResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateGroupResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateGroupResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateGroupResponseMultiError, or nil if none found.
func (m *CreateGroupResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateGroupResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroup()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateGroupResponseValidationError{
					field:  "Group",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateGroupResponseValidationError{
					field:  "Group",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroup()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateGroupResponseValidationError{
				field:  "Group",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Success

	// no validation rules for ErrorMessage

	if len(errors) > 0 {
		return CreateGroupResponseMultiError(errors)
	}

	return nil
}

// CreateGroupResponseMultiError is an error wrapping multiple validation
// errors returned by CreateGroupResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateGroupResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateGroupResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateGroupResponseMultiError) AllErrors() []error { return m }

// CreateGroupResponseValidationError is the validation error returned by
// CreateGroupResponse.Validate if the designated constraints aren't met.
type CreateGroupResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateGroupResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateGroupResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateGroupResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateGroupResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateGroupResponseValidationError) ErrorName() string {
	return "CreateGroupResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateGroupResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateGroupResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateGroupResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateGroupResponseValidationError{}

// Validate checks the field values on GetGroupInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGroupInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGroupInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGroupInfoRequestMultiError, or nil if none found.
func (m *GetGroupInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGroupInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	if len(errors) > 0 {
		return GetGroupInfoRequestMultiError(errors)
	}

	return nil
}

// GetGroupInfoRequestMultiError is an error wrapping multiple validation
// errors returned by GetGroupInfoRequest.ValidateAll() if the designated
// constraints aren't met.
type GetGroupInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGroupInfoRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGroupInfoRequestMultiError) AllErrors() []error { return m }

// GetGroupInfoRequestValidationError is the validation error returned by
// GetGroupInfoRequest.Validate if the designated constraints aren't met.
type GetGroupInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGroupInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGroupInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGroupInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGroupInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGroupInfoRequestValidationError) ErrorName() string {
	return "GetGroupInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetGroupInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGroupInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGroupInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGroupInfoRequestValidationError{}

// Validate checks the field values on GetGroupInfoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGroupInfoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGroupInfoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGroupInfoResponseMultiError, or nil if none found.
func (m *GetGroupInfoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGroupInfoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroup()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetGroupInfoResponseValidationError{
					field:  "Group",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetGroupInfoResponseValidationError{
					field:  "Group",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroup()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetGroupInfoResponseValidationError{
				field:  "Group",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetMembers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetGroupInfoResponseValidationError{
						field:  fmt.Sprintf("Members[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetGroupInfoResponseValidationError{
						field:  fmt.Sprintf("Members[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetGroupInfoResponseValidationError{
					field:  fmt.Sprintf("Members[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetGroupInfoResponseMultiError(errors)
	}

	return nil
}

// GetGroupInfoResponseMultiError is an error wrapping multiple validation
// errors returned by GetGroupInfoResponse.ValidateAll() if the designated
// constraints aren't met.
type GetGroupInfoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGroupInfoResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGroupInfoResponseMultiError) AllErrors() []error { return m }

// GetGroupInfoResponseValidationError is the validation error returned by
// GetGroupInfoResponse.Validate if the designated constraints aren't met.
type GetGroupInfoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGroupInfoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGroupInfoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGroupInfoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGroupInfoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGroupInfoResponseValidationError) ErrorName() string {
	return "GetGroupInfoResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetGroupInfoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGroupInfoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGroupInfoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGroupInfoResponseValidationError{}

// Validate checks the field values on GetUserGroupsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserGroupsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserGroupsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserGroupsRequestMultiError, or nil if none found.
func (m *GetUserGroupsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserGroupsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetUserGroupsRequestMultiError(errors)
	}

	return nil
}

// GetUserGroupsRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserGroupsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetUserGroupsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserGroupsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserGroupsRequestMultiError) AllErrors() []error { return m }

// GetUserGroupsRequestValidationError is the validation error returned by
// GetUserGroupsRequest.Validate if the designated constraints aren't met.
type GetUserGroupsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserGroupsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserGroupsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserGroupsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserGroupsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserGroupsRequestValidationError) ErrorName() string {
	return "GetUserGroupsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserGroupsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserGroupsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserGroupsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserGroupsRequestValidationError{}

// Validate checks the field values on GetUserGroupsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserGroupsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserGroupsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserGroupsResponseMultiError, or nil if none found.
func (m *GetUserGroupsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserGroupsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetGroups() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserGroupsResponseValidationError{
						field:  fmt.Sprintf("Groups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserGroupsResponseValidationError{
						field:  fmt.Sprintf("Groups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserGroupsResponseValidationError{
					field:  fmt.Sprintf("Groups[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalCount

	if len(errors) > 0 {
		return GetUserGroupsResponseMultiError(errors)
	}

	return nil
}

// GetUserGroupsResponseMultiError is an error wrapping multiple validation
// errors returned by GetUserGroupsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetUserGroupsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserGroupsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserGroupsResponseMultiError) AllErrors() []error { return m }

// GetUserGroupsResponseValidationError is the validation error returned by
// GetUserGroupsResponse.Validate if the designated constraints aren't met.
type GetUserGroupsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserGroupsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserGroupsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserGroupsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserGroupsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserGroupsResponseValidationError) ErrorName() string {
	return "GetUserGroupsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserGroupsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserGroupsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserGroupsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserGroupsResponseValidationError{}

// Validate checks the field values on AddGroupMembersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddGroupMembersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddGroupMembersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddGroupMembersRequestMultiError, or nil if none found.
func (m *AddGroupMembersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddGroupMembersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	if len(errors) > 0 {
		return AddGroupMembersRequestMultiError(errors)
	}

	return nil
}

// AddGroupMembersRequestMultiError is an error wrapping multiple validation
// errors returned by AddGroupMembersRequest.ValidateAll() if the designated
// constraints aren't met.
type AddGroupMembersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddGroupMembersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddGroupMembersRequestMultiError) AllErrors() []error { return m }

// AddGroupMembersRequestValidationError is the validation error returned by
// AddGroupMembersRequest.Validate if the designated constraints aren't met.
type AddGroupMembersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddGroupMembersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddGroupMembersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddGroupMembersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddGroupMembersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddGroupMembersRequestValidationError) ErrorName() string {
	return "AddGroupMembersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AddGroupMembersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddGroupMembersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddGroupMembersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddGroupMembersRequestValidationError{}

// Validate checks the field values on AddGroupMembersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddGroupMembersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddGroupMembersResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddGroupMembersResponseMultiError, or nil if none found.
func (m *AddGroupMembersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddGroupMembersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for AddedCount

	// no validation rules for ErrorMessage

	if len(errors) > 0 {
		return AddGroupMembersResponseMultiError(errors)
	}

	return nil
}

// AddGroupMembersResponseMultiError is an error wrapping multiple validation
// errors returned by AddGroupMembersResponse.ValidateAll() if the designated
// constraints aren't met.
type AddGroupMembersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddGroupMembersResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddGroupMembersResponseMultiError) AllErrors() []error { return m }

// AddGroupMembersResponseValidationError is the validation error returned by
// AddGroupMembersResponse.Validate if the designated constraints aren't met.
type AddGroupMembersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddGroupMembersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddGroupMembersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddGroupMembersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddGroupMembersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddGroupMembersResponseValidationError) ErrorName() string {
	return "AddGroupMembersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AddGroupMembersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddGroupMembersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddGroupMembersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddGroupMembersResponseValidationError{}

// Validate checks the field values on RemoveGroupMemberRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RemoveGroupMemberRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveGroupMemberRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoveGroupMemberRequestMultiError, or nil if none found.
func (m *RemoveGroupMemberRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveGroupMemberRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for UserId

	if len(errors) > 0 {
		return RemoveGroupMemberRequestMultiError(errors)
	}

	return nil
}

// RemoveGroupMemberRequestMultiError is an error wrapping multiple validation
// errors returned by RemoveGroupMemberRequest.ValidateAll() if the designated
// constraints aren't met.
type RemoveGroupMemberRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveGroupMemberRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveGroupMemberRequestMultiError) AllErrors() []error { return m }

// RemoveGroupMemberRequestValidationError is the validation error returned by
// RemoveGroupMemberRequest.Validate if the designated constraints aren't met.
type RemoveGroupMemberRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveGroupMemberRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveGroupMemberRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveGroupMemberRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveGroupMemberRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveGroupMemberRequestValidationError) ErrorName() string {
	return "RemoveGroupMemberRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveGroupMemberRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveGroupMemberRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveGroupMemberRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveGroupMemberRequestValidationError{}

// Validate checks the field values on RemoveGroupMemberResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RemoveGroupMemberResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveGroupMemberResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoveGroupMemberResponseMultiError, or nil if none found.
func (m *RemoveGroupMemberResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveGroupMemberResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for ErrorMessage

	if len(errors) > 0 {
		return RemoveGroupMemberResponseMultiError(errors)
	}

	return nil
}

// RemoveGroupMemberResponseMultiError is an error wrapping multiple validation
// errors returned by RemoveGroupMemberResponse.ValidateAll() if the
// designated constraints aren't met.
type RemoveGroupMemberResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveGroupMemberResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveGroupMemberResponseMultiError) AllErrors() []error { return m }

// RemoveGroupMemberResponseValidationError is the validation error returned by
// RemoveGroupMemberResponse.Validate if the designated constraints aren't met.
type RemoveGroupMemberResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveGroupMemberResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveGroupMemberResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveGroupMemberResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveGroupMemberResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveGroupMemberResponseValidationError) ErrorName() string {
	return "RemoveGroupMemberResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveGroupMemberResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveGroupMemberResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveGroupMemberResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveGroupMemberResponseValidationError{}

// Validate checks the field values on GetGroupMembersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGroupMembersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGroupMembersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGroupMembersRequestMultiError, or nil if none found.
func (m *GetGroupMembersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGroupMembersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	if len(errors) > 0 {
		return GetGroupMembersRequestMultiError(errors)
	}

	return nil
}

// GetGroupMembersRequestMultiError is an error wrapping multiple validation
// errors returned by GetGroupMembersRequest.ValidateAll() if the designated
// constraints aren't met.
type GetGroupMembersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGroupMembersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGroupMembersRequestMultiError) AllErrors() []error { return m }

// GetGroupMembersRequestValidationError is the validation error returned by
// GetGroupMembersRequest.Validate if the designated constraints aren't met.
type GetGroupMembersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGroupMembersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGroupMembersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGroupMembersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGroupMembersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGroupMembersRequestValidationError) ErrorName() string {
	return "GetGroupMembersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetGroupMembersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGroupMembersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGroupMembersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGroupMembersRequestValidationError{}

// Validate checks the field values on GetGroupMembersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGroupMembersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGroupMembersResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGroupMembersResponseMultiError, or nil if none found.
func (m *GetGroupMembersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGroupMembersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMembers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetGroupMembersResponseValidationError{
						field:  fmt.Sprintf("Members[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetGroupMembersResponseValidationError{
						field:  fmt.Sprintf("Members[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetGroupMembersResponseValidationError{
					field:  fmt.Sprintf("Members[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalCount

	if len(errors) > 0 {
		return GetGroupMembersResponseMultiError(errors)
	}

	return nil
}

// GetGroupMembersResponseMultiError is an error wrapping multiple validation
// errors returned by GetGroupMembersResponse.ValidateAll() if the designated
// constraints aren't met.
type GetGroupMembersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGroupMembersResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGroupMembersResponseMultiError) AllErrors() []error { return m }

// GetGroupMembersResponseValidationError is the validation error returned by
// GetGroupMembersResponse.Validate if the designated constraints aren't met.
type GetGroupMembersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGroupMembersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGroupMembersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGroupMembersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGroupMembersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGroupMembersResponseValidationError) ErrorName() string {
	return "GetGroupMembersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetGroupMembersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGroupMembersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGroupMembersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGroupMembersResponseValidationError{}

// Validate checks the field values on UpdateGroupInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateGroupInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGroupInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateGroupInfoRequestMultiError, or nil if none found.
func (m *UpdateGroupInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGroupInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for Name

	// no validation rules for Avatar

	// no validation rules for Notice

	if len(errors) > 0 {
		return UpdateGroupInfoRequestMultiError(errors)
	}

	return nil
}

// UpdateGroupInfoRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateGroupInfoRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateGroupInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGroupInfoRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGroupInfoRequestMultiError) AllErrors() []error { return m }

// UpdateGroupInfoRequestValidationError is the validation error returned by
// UpdateGroupInfoRequest.Validate if the designated constraints aren't met.
type UpdateGroupInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGroupInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGroupInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGroupInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGroupInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGroupInfoRequestValidationError) ErrorName() string {
	return "UpdateGroupInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateGroupInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGroupInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGroupInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGroupInfoRequestValidationError{}

// Validate checks the field values on UpdateGroupInfoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateGroupInfoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGroupInfoResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateGroupInfoResponseMultiError, or nil if none found.
func (m *UpdateGroupInfoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGroupInfoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroup()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateGroupInfoResponseValidationError{
					field:  "Group",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateGroupInfoResponseValidationError{
					field:  "Group",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroup()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateGroupInfoResponseValidationError{
				field:  "Group",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Success

	// no validation rules for ErrorMessage

	if len(errors) > 0 {
		return UpdateGroupInfoResponseMultiError(errors)
	}

	return nil
}

// UpdateGroupInfoResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateGroupInfoResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateGroupInfoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGroupInfoResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGroupInfoResponseMultiError) AllErrors() []error { return m }

// UpdateGroupInfoResponseValidationError is the validation error returned by
// UpdateGroupInfoResponse.Validate if the designated constraints aren't met.
type UpdateGroupInfoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGroupInfoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGroupInfoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGroupInfoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGroupInfoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGroupInfoResponseValidationError) ErrorName() string {
	return "UpdateGroupInfoResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateGroupInfoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGroupInfoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGroupInfoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGroupInfoResponseValidationError{}

// Validate checks the field values on CheckMemberInGroupRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckMemberInGroupRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckMemberInGroupRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckMemberInGroupRequestMultiError, or nil if none found.
func (m *CheckMemberInGroupRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckMemberInGroupRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for UserId

	if len(errors) > 0 {
		return CheckMemberInGroupRequestMultiError(errors)
	}

	return nil
}

// CheckMemberInGroupRequestMultiError is an error wrapping multiple validation
// errors returned by CheckMemberInGroupRequest.ValidateAll() if the
// designated constraints aren't met.
type CheckMemberInGroupRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckMemberInGroupRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckMemberInGroupRequestMultiError) AllErrors() []error { return m }

// CheckMemberInGroupRequestValidationError is the validation error returned by
// CheckMemberInGroupRequest.Validate if the designated constraints aren't met.
type CheckMemberInGroupRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckMemberInGroupRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckMemberInGroupRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckMemberInGroupRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckMemberInGroupRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckMemberInGroupRequestValidationError) ErrorName() string {
	return "CheckMemberInGroupRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CheckMemberInGroupRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckMemberInGroupRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckMemberInGroupRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckMemberInGroupRequestValidationError{}

// Validate checks the field values on CheckMemberInGroupResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckMemberInGroupResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckMemberInGroupResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckMemberInGroupResponseMultiError, or nil if none found.
func (m *CheckMemberInGroupResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckMemberInGroupResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsMember

	// no validation rules for Role

	if len(errors) > 0 {
		return CheckMemberInGroupResponseMultiError(errors)
	}

	return nil
}

// CheckMemberInGroupResponseMultiError is an error wrapping multiple
// validation errors returned by CheckMemberInGroupResponse.ValidateAll() if
// the designated constraints aren't met.
type CheckMemberInGroupResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckMemberInGroupResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckMemberInGroupResponseMultiError) AllErrors() []error { return m }

// CheckMemberInGroupResponseValidationError is the validation error returned
// by CheckMemberInGroupResponse.Validate if the designated constraints aren't met.
type CheckMemberInGroupResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckMemberInGroupResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckMemberInGroupResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckMemberInGroupResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckMemberInGroupResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckMemberInGroupResponseValidationError) ErrorName() string {
	return "CheckMemberInGroupResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CheckMemberInGroupResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckMemberInGroupResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckMemberInGroupResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckMemberInGroupResponseValidationError{}
