mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  database: gochat

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  db: 0

token:
  encryptionKey: examplekey946666
  expire: 24 # token过期时间，单位小时