app:
  mode: dev
  api_port: 8080
  admin_port: 8081

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  database: gochat

redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0

mongodb:
  uri: mongodb://root:password@127.0.0.1:27017
  database: gochat

websocket:
  port: 8082
  read_buffer_size: 1024
  write_buffer_size: 1024

token:
  encryptionKey: examplekey946666
  expire: 24 # token过期时间，单位小时