// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/finance/finance.proto

package finance

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetFinanceConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetFinanceConfigRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFinanceConfigRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFinanceConfigRequestMultiError, or nil if none found.
func (m *GetFinanceConfigRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFinanceConfigRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetFinanceConfigRequestMultiError(errors)
	}

	return nil
}

// GetFinanceConfigRequestMultiError is an error wrapping multiple validation
// errors returned by GetFinanceConfigRequest.ValidateAll() if the designated
// constraints aren't met.
type GetFinanceConfigRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFinanceConfigRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFinanceConfigRequestMultiError) AllErrors() []error { return m }

// GetFinanceConfigRequestValidationError is the validation error returned by
// GetFinanceConfigRequest.Validate if the designated constraints aren't met.
type GetFinanceConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFinanceConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFinanceConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFinanceConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFinanceConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFinanceConfigRequestValidationError) ErrorName() string {
	return "GetFinanceConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetFinanceConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFinanceConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFinanceConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFinanceConfigRequestValidationError{}

// Validate checks the field values on GetFinanceConfigResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetFinanceConfigResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFinanceConfigResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFinanceConfigResponseMultiError, or nil if none found.
func (m *GetFinanceConfigResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFinanceConfigResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RechargeEnabled

	// no validation rules for WithdrawEnabled

	// no validation rules for RechargeDailyLimit

	// no validation rules for WithdrawDailyLimit

	// no validation rules for WithdrawDailyCount

	// no validation rules for WithdrawFeeRate

	if len(errors) > 0 {
		return GetFinanceConfigResponseMultiError(errors)
	}

	return nil
}

// GetFinanceConfigResponseMultiError is an error wrapping multiple validation
// errors returned by GetFinanceConfigResponse.ValidateAll() if the designated
// constraints aren't met.
type GetFinanceConfigResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFinanceConfigResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFinanceConfigResponseMultiError) AllErrors() []error { return m }

// GetFinanceConfigResponseValidationError is the validation error returned by
// GetFinanceConfigResponse.Validate if the designated constraints aren't met.
type GetFinanceConfigResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFinanceConfigResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFinanceConfigResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFinanceConfigResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFinanceConfigResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFinanceConfigResponseValidationError) ErrorName() string {
	return "GetFinanceConfigResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetFinanceConfigResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFinanceConfigResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFinanceConfigResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFinanceConfigResponseValidationError{}

// Validate checks the field values on UpdateFinanceConfigRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateFinanceConfigRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateFinanceConfigRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateFinanceConfigRequestMultiError, or nil if none found.
func (m *UpdateFinanceConfigRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateFinanceConfigRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RechargeEnabled

	// no validation rules for WithdrawEnabled

	// no validation rules for RechargeDailyLimit

	// no validation rules for WithdrawDailyLimit

	// no validation rules for WithdrawDailyCount

	// no validation rules for WithdrawFeeRate

	if len(errors) > 0 {
		return UpdateFinanceConfigRequestMultiError(errors)
	}

	return nil
}

// UpdateFinanceConfigRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateFinanceConfigRequest.ValidateAll() if
// the designated constraints aren't met.
type UpdateFinanceConfigRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateFinanceConfigRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateFinanceConfigRequestMultiError) AllErrors() []error { return m }

// UpdateFinanceConfigRequestValidationError is the validation error returned
// by UpdateFinanceConfigRequest.Validate if the designated constraints aren't met.
type UpdateFinanceConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateFinanceConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateFinanceConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateFinanceConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateFinanceConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateFinanceConfigRequestValidationError) ErrorName() string {
	return "UpdateFinanceConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateFinanceConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateFinanceConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateFinanceConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateFinanceConfigRequestValidationError{}

// Validate checks the field values on UpdateFinanceConfigResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateFinanceConfigResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateFinanceConfigResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateFinanceConfigResponseMultiError, or nil if none found.
func (m *UpdateFinanceConfigResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateFinanceConfigResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return UpdateFinanceConfigResponseMultiError(errors)
	}

	return nil
}

// UpdateFinanceConfigResponseMultiError is an error wrapping multiple
// validation errors returned by UpdateFinanceConfigResponse.ValidateAll() if
// the designated constraints aren't met.
type UpdateFinanceConfigResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateFinanceConfigResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateFinanceConfigResponseMultiError) AllErrors() []error { return m }

// UpdateFinanceConfigResponseValidationError is the validation error returned
// by UpdateFinanceConfigResponse.Validate if the designated constraints
// aren't met.
type UpdateFinanceConfigResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateFinanceConfigResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateFinanceConfigResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateFinanceConfigResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateFinanceConfigResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateFinanceConfigResponseValidationError) ErrorName() string {
	return "UpdateFinanceConfigResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateFinanceConfigResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateFinanceConfigResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateFinanceConfigResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateFinanceConfigResponseValidationError{}

// Validate checks the field values on GetFinanceRecordsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetFinanceRecordsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFinanceRecordsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFinanceRecordsRequestMultiError, or nil if none found.
func (m *GetFinanceRecordsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFinanceRecordsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for UserId

	// no validation rules for Type

	// no validation rules for StartTime

	// no validation rules for EndTime

	if len(errors) > 0 {
		return GetFinanceRecordsRequestMultiError(errors)
	}

	return nil
}

// GetFinanceRecordsRequestMultiError is an error wrapping multiple validation
// errors returned by GetFinanceRecordsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetFinanceRecordsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFinanceRecordsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFinanceRecordsRequestMultiError) AllErrors() []error { return m }

// GetFinanceRecordsRequestValidationError is the validation error returned by
// GetFinanceRecordsRequest.Validate if the designated constraints aren't met.
type GetFinanceRecordsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFinanceRecordsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFinanceRecordsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFinanceRecordsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFinanceRecordsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFinanceRecordsRequestValidationError) ErrorName() string {
	return "GetFinanceRecordsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetFinanceRecordsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFinanceRecordsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFinanceRecordsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFinanceRecordsRequestValidationError{}

// Validate checks the field values on GetFinanceRecordsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetFinanceRecordsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFinanceRecordsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFinanceRecordsResponseMultiError, or nil if none found.
func (m *GetFinanceRecordsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFinanceRecordsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRecords() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetFinanceRecordsResponseValidationError{
						field:  fmt.Sprintf("Records[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetFinanceRecordsResponseValidationError{
						field:  fmt.Sprintf("Records[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetFinanceRecordsResponseValidationError{
					field:  fmt.Sprintf("Records[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return GetFinanceRecordsResponseMultiError(errors)
	}

	return nil
}

// GetFinanceRecordsResponseMultiError is an error wrapping multiple validation
// errors returned by GetFinanceRecordsResponse.ValidateAll() if the
// designated constraints aren't met.
type GetFinanceRecordsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFinanceRecordsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFinanceRecordsResponseMultiError) AllErrors() []error { return m }

// GetFinanceRecordsResponseValidationError is the validation error returned by
// GetFinanceRecordsResponse.Validate if the designated constraints aren't met.
type GetFinanceRecordsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFinanceRecordsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFinanceRecordsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFinanceRecordsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFinanceRecordsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFinanceRecordsResponseValidationError) ErrorName() string {
	return "GetFinanceRecordsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetFinanceRecordsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFinanceRecordsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFinanceRecordsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFinanceRecordsResponseValidationError{}

// Validate checks the field values on FinanceRecord with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FinanceRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FinanceRecord with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FinanceRecordMultiError, or
// nil if none found.
func (m *FinanceRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *FinanceRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Type

	// no validation rules for Amount

	// no validation rules for Balance

	// no validation rules for RelatedId

	// no validation rules for Remark

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FinanceRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FinanceRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FinanceRecordValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FinanceRecordMultiError(errors)
	}

	return nil
}

// FinanceRecordMultiError is an error wrapping multiple validation errors
// returned by FinanceRecord.ValidateAll() if the designated constraints
// aren't met.
type FinanceRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FinanceRecordMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FinanceRecordMultiError) AllErrors() []error { return m }

// FinanceRecordValidationError is the validation error returned by
// FinanceRecord.Validate if the designated constraints aren't met.
type FinanceRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FinanceRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FinanceRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FinanceRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FinanceRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FinanceRecordValidationError) ErrorName() string { return "FinanceRecordValidationError" }

// Error satisfies the builtin error interface
func (e FinanceRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFinanceRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FinanceRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FinanceRecordValidationError{}

// Validate checks the field values on GetPendingRechargesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPendingRechargesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPendingRechargesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPendingRechargesRequestMultiError, or nil if none found.
func (m *GetPendingRechargesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPendingRechargesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return GetPendingRechargesRequestMultiError(errors)
	}

	return nil
}

// GetPendingRechargesRequestMultiError is an error wrapping multiple
// validation errors returned by GetPendingRechargesRequest.ValidateAll() if
// the designated constraints aren't met.
type GetPendingRechargesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPendingRechargesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPendingRechargesRequestMultiError) AllErrors() []error { return m }

// GetPendingRechargesRequestValidationError is the validation error returned
// by GetPendingRechargesRequest.Validate if the designated constraints aren't met.
type GetPendingRechargesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPendingRechargesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPendingRechargesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPendingRechargesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPendingRechargesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPendingRechargesRequestValidationError) ErrorName() string {
	return "GetPendingRechargesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetPendingRechargesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPendingRechargesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPendingRechargesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPendingRechargesRequestValidationError{}

// Validate checks the field values on GetPendingRechargesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPendingRechargesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPendingRechargesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPendingRechargesResponseMultiError, or nil if none found.
func (m *GetPendingRechargesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPendingRechargesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRecharges() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetPendingRechargesResponseValidationError{
						field:  fmt.Sprintf("Recharges[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetPendingRechargesResponseValidationError{
						field:  fmt.Sprintf("Recharges[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetPendingRechargesResponseValidationError{
					field:  fmt.Sprintf("Recharges[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return GetPendingRechargesResponseMultiError(errors)
	}

	return nil
}

// GetPendingRechargesResponseMultiError is an error wrapping multiple
// validation errors returned by GetPendingRechargesResponse.ValidateAll() if
// the designated constraints aren't met.
type GetPendingRechargesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPendingRechargesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPendingRechargesResponseMultiError) AllErrors() []error { return m }

// GetPendingRechargesResponseValidationError is the validation error returned
// by GetPendingRechargesResponse.Validate if the designated constraints
// aren't met.
type GetPendingRechargesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPendingRechargesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPendingRechargesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPendingRechargesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPendingRechargesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPendingRechargesResponseValidationError) ErrorName() string {
	return "GetPendingRechargesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPendingRechargesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPendingRechargesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPendingRechargesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPendingRechargesResponseValidationError{}

// Validate checks the field values on RechargeInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RechargeInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RechargeInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RechargeInfoMultiError, or
// nil if none found.
func (m *RechargeInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *RechargeInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for UserName

	// no validation rules for Amount

	// no validation rules for Status

	// no validation rules for Remark

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RechargeInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RechargeInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RechargeInfoValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RechargeInfoMultiError(errors)
	}

	return nil
}

// RechargeInfoMultiError is an error wrapping multiple validation errors
// returned by RechargeInfo.ValidateAll() if the designated constraints aren't met.
type RechargeInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RechargeInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RechargeInfoMultiError) AllErrors() []error { return m }

// RechargeInfoValidationError is the validation error returned by
// RechargeInfo.Validate if the designated constraints aren't met.
type RechargeInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RechargeInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RechargeInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RechargeInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RechargeInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RechargeInfoValidationError) ErrorName() string { return "RechargeInfoValidationError" }

// Error satisfies the builtin error interface
func (e RechargeInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRechargeInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RechargeInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RechargeInfoValidationError{}

// Validate checks the field values on AuditRechargeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuditRechargeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuditRechargeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuditRechargeRequestMultiError, or nil if none found.
func (m *AuditRechargeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuditRechargeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := AuditRechargeRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _AuditRechargeRequest_Action_InLookup[m.GetAction()]; !ok {
		err := AuditRechargeRequestValidationError{
			field:  "Action",
			reason: "value must be in list [approve reject]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Note

	if len(errors) > 0 {
		return AuditRechargeRequestMultiError(errors)
	}

	return nil
}

// AuditRechargeRequestMultiError is an error wrapping multiple validation
// errors returned by AuditRechargeRequest.ValidateAll() if the designated
// constraints aren't met.
type AuditRechargeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuditRechargeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuditRechargeRequestMultiError) AllErrors() []error { return m }

// AuditRechargeRequestValidationError is the validation error returned by
// AuditRechargeRequest.Validate if the designated constraints aren't met.
type AuditRechargeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuditRechargeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuditRechargeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuditRechargeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuditRechargeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuditRechargeRequestValidationError) ErrorName() string {
	return "AuditRechargeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AuditRechargeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuditRechargeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuditRechargeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuditRechargeRequestValidationError{}

var _AuditRechargeRequest_Action_InLookup = map[string]struct{}{
	"approve": {},
	"reject":  {},
}

// Validate checks the field values on AuditRechargeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuditRechargeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuditRechargeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuditRechargeResponseMultiError, or nil if none found.
func (m *AuditRechargeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuditRechargeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return AuditRechargeResponseMultiError(errors)
	}

	return nil
}

// AuditRechargeResponseMultiError is an error wrapping multiple validation
// errors returned by AuditRechargeResponse.ValidateAll() if the designated
// constraints aren't met.
type AuditRechargeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuditRechargeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuditRechargeResponseMultiError) AllErrors() []error { return m }

// AuditRechargeResponseValidationError is the validation error returned by
// AuditRechargeResponse.Validate if the designated constraints aren't met.
type AuditRechargeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuditRechargeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuditRechargeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuditRechargeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuditRechargeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuditRechargeResponseValidationError) ErrorName() string {
	return "AuditRechargeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuditRechargeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuditRechargeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuditRechargeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuditRechargeResponseValidationError{}

// Validate checks the field values on GetPendingWithdrawsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPendingWithdrawsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPendingWithdrawsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPendingWithdrawsRequestMultiError, or nil if none found.
func (m *GetPendingWithdrawsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPendingWithdrawsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return GetPendingWithdrawsRequestMultiError(errors)
	}

	return nil
}

// GetPendingWithdrawsRequestMultiError is an error wrapping multiple
// validation errors returned by GetPendingWithdrawsRequest.ValidateAll() if
// the designated constraints aren't met.
type GetPendingWithdrawsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPendingWithdrawsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPendingWithdrawsRequestMultiError) AllErrors() []error { return m }

// GetPendingWithdrawsRequestValidationError is the validation error returned
// by GetPendingWithdrawsRequest.Validate if the designated constraints aren't met.
type GetPendingWithdrawsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPendingWithdrawsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPendingWithdrawsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPendingWithdrawsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPendingWithdrawsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPendingWithdrawsRequestValidationError) ErrorName() string {
	return "GetPendingWithdrawsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetPendingWithdrawsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPendingWithdrawsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPendingWithdrawsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPendingWithdrawsRequestValidationError{}

// Validate checks the field values on GetPendingWithdrawsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPendingWithdrawsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPendingWithdrawsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPendingWithdrawsResponseMultiError, or nil if none found.
func (m *GetPendingWithdrawsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPendingWithdrawsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetWithdraws() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetPendingWithdrawsResponseValidationError{
						field:  fmt.Sprintf("Withdraws[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetPendingWithdrawsResponseValidationError{
						field:  fmt.Sprintf("Withdraws[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetPendingWithdrawsResponseValidationError{
					field:  fmt.Sprintf("Withdraws[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return GetPendingWithdrawsResponseMultiError(errors)
	}

	return nil
}

// GetPendingWithdrawsResponseMultiError is an error wrapping multiple
// validation errors returned by GetPendingWithdrawsResponse.ValidateAll() if
// the designated constraints aren't met.
type GetPendingWithdrawsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPendingWithdrawsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPendingWithdrawsResponseMultiError) AllErrors() []error { return m }

// GetPendingWithdrawsResponseValidationError is the validation error returned
// by GetPendingWithdrawsResponse.Validate if the designated constraints
// aren't met.
type GetPendingWithdrawsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPendingWithdrawsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPendingWithdrawsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPendingWithdrawsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPendingWithdrawsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPendingWithdrawsResponseValidationError) ErrorName() string {
	return "GetPendingWithdrawsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPendingWithdrawsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPendingWithdrawsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPendingWithdrawsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPendingWithdrawsResponseValidationError{}

// Validate checks the field values on WithdrawInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WithdrawInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WithdrawInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WithdrawInfoMultiError, or
// nil if none found.
func (m *WithdrawInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *WithdrawInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for UserName

	// no validation rules for Amount

	// no validation rules for Fee

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawInfoValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WithdrawInfoMultiError(errors)
	}

	return nil
}

// WithdrawInfoMultiError is an error wrapping multiple validation errors
// returned by WithdrawInfo.ValidateAll() if the designated constraints aren't met.
type WithdrawInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WithdrawInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WithdrawInfoMultiError) AllErrors() []error { return m }

// WithdrawInfoValidationError is the validation error returned by
// WithdrawInfo.Validate if the designated constraints aren't met.
type WithdrawInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WithdrawInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WithdrawInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WithdrawInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WithdrawInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WithdrawInfoValidationError) ErrorName() string { return "WithdrawInfoValidationError" }

// Error satisfies the builtin error interface
func (e WithdrawInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWithdrawInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WithdrawInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WithdrawInfoValidationError{}

// Validate checks the field values on AuditWithdrawRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuditWithdrawRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuditWithdrawRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuditWithdrawRequestMultiError, or nil if none found.
func (m *AuditWithdrawRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuditWithdrawRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := AuditWithdrawRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _AuditWithdrawRequest_Action_InLookup[m.GetAction()]; !ok {
		err := AuditWithdrawRequestValidationError{
			field:  "Action",
			reason: "value must be in list [approve reject]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Note

	if len(errors) > 0 {
		return AuditWithdrawRequestMultiError(errors)
	}

	return nil
}

// AuditWithdrawRequestMultiError is an error wrapping multiple validation
// errors returned by AuditWithdrawRequest.ValidateAll() if the designated
// constraints aren't met.
type AuditWithdrawRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuditWithdrawRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuditWithdrawRequestMultiError) AllErrors() []error { return m }

// AuditWithdrawRequestValidationError is the validation error returned by
// AuditWithdrawRequest.Validate if the designated constraints aren't met.
type AuditWithdrawRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuditWithdrawRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuditWithdrawRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuditWithdrawRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuditWithdrawRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuditWithdrawRequestValidationError) ErrorName() string {
	return "AuditWithdrawRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AuditWithdrawRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuditWithdrawRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuditWithdrawRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuditWithdrawRequestValidationError{}

var _AuditWithdrawRequest_Action_InLookup = map[string]struct{}{
	"approve": {},
	"reject":  {},
}

// Validate checks the field values on AuditWithdrawResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuditWithdrawResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuditWithdrawResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuditWithdrawResponseMultiError, or nil if none found.
func (m *AuditWithdrawResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuditWithdrawResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return AuditWithdrawResponseMultiError(errors)
	}

	return nil
}

// AuditWithdrawResponseMultiError is an error wrapping multiple validation
// errors returned by AuditWithdrawResponse.ValidateAll() if the designated
// constraints aren't met.
type AuditWithdrawResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuditWithdrawResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuditWithdrawResponseMultiError) AllErrors() []error { return m }

// AuditWithdrawResponseValidationError is the validation error returned by
// AuditWithdrawResponse.Validate if the designated constraints aren't met.
type AuditWithdrawResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuditWithdrawResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuditWithdrawResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuditWithdrawResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuditWithdrawResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuditWithdrawResponseValidationError) ErrorName() string {
	return "AuditWithdrawResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuditWithdrawResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuditWithdrawResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuditWithdrawResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuditWithdrawResponseValidationError{}

// Validate checks the field values on AdjustBalanceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AdjustBalanceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdjustBalanceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AdjustBalanceRequestMultiError, or nil if none found.
func (m *AdjustBalanceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AdjustBalanceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := AdjustBalanceRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Amount

	if utf8.RuneCountInString(m.GetReason()) < 1 {
		err := AdjustBalanceRequestValidationError{
			field:  "Reason",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AdjustBalanceRequestMultiError(errors)
	}

	return nil
}

// AdjustBalanceRequestMultiError is an error wrapping multiple validation
// errors returned by AdjustBalanceRequest.ValidateAll() if the designated
// constraints aren't met.
type AdjustBalanceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdjustBalanceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdjustBalanceRequestMultiError) AllErrors() []error { return m }

// AdjustBalanceRequestValidationError is the validation error returned by
// AdjustBalanceRequest.Validate if the designated constraints aren't met.
type AdjustBalanceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdjustBalanceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdjustBalanceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdjustBalanceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdjustBalanceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdjustBalanceRequestValidationError) ErrorName() string {
	return "AdjustBalanceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AdjustBalanceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdjustBalanceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdjustBalanceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdjustBalanceRequestValidationError{}

// Validate checks the field values on AdjustBalanceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AdjustBalanceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdjustBalanceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AdjustBalanceResponseMultiError, or nil if none found.
func (m *AdjustBalanceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AdjustBalanceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return AdjustBalanceResponseMultiError(errors)
	}

	return nil
}

// AdjustBalanceResponseMultiError is an error wrapping multiple validation
// errors returned by AdjustBalanceResponse.ValidateAll() if the designated
// constraints aren't met.
type AdjustBalanceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdjustBalanceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdjustBalanceResponseMultiError) AllErrors() []error { return m }

// AdjustBalanceResponseValidationError is the validation error returned by
// AdjustBalanceResponse.Validate if the designated constraints aren't met.
type AdjustBalanceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdjustBalanceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdjustBalanceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdjustBalanceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdjustBalanceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdjustBalanceResponseValidationError) ErrorName() string {
	return "AdjustBalanceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AdjustBalanceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdjustBalanceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdjustBalanceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdjustBalanceResponseValidationError{}
