// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: admin/finance/finance.proto

package finance

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取资金配置请求
type GetFinanceConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFinanceConfigRequest) Reset() {
	*x = GetFinanceConfigRequest{}
	mi := &file_admin_finance_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFinanceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFinanceConfigRequest) ProtoMessage() {}

func (x *GetFinanceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFinanceConfigRequest.ProtoReflect.Descriptor instead.
func (*GetFinanceConfigRequest) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{0}
}

// 获取资金配置响应
type GetFinanceConfigResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RechargeEnabled    bool                   `protobuf:"varint,1,opt,name=recharge_enabled,json=rechargeEnabled,proto3" json:"recharge_enabled,omitempty"`
	WithdrawEnabled    bool                   `protobuf:"varint,2,opt,name=withdraw_enabled,json=withdrawEnabled,proto3" json:"withdraw_enabled,omitempty"`
	RechargeDailyLimit int64                  `protobuf:"varint,3,opt,name=recharge_daily_limit,json=rechargeDailyLimit,proto3" json:"recharge_daily_limit,omitempty"`
	WithdrawDailyLimit int64                  `protobuf:"varint,4,opt,name=withdraw_daily_limit,json=withdrawDailyLimit,proto3" json:"withdraw_daily_limit,omitempty"`
	WithdrawDailyCount int32                  `protobuf:"varint,5,opt,name=withdraw_daily_count,json=withdrawDailyCount,proto3" json:"withdraw_daily_count,omitempty"`
	WithdrawFeeRate    int64                  `protobuf:"varint,6,opt,name=withdraw_fee_rate,json=withdrawFeeRate,proto3" json:"withdraw_fee_rate,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetFinanceConfigResponse) Reset() {
	*x = GetFinanceConfigResponse{}
	mi := &file_admin_finance_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFinanceConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFinanceConfigResponse) ProtoMessage() {}

func (x *GetFinanceConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFinanceConfigResponse.ProtoReflect.Descriptor instead.
func (*GetFinanceConfigResponse) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{1}
}

func (x *GetFinanceConfigResponse) GetRechargeEnabled() bool {
	if x != nil {
		return x.RechargeEnabled
	}
	return false
}

func (x *GetFinanceConfigResponse) GetWithdrawEnabled() bool {
	if x != nil {
		return x.WithdrawEnabled
	}
	return false
}

func (x *GetFinanceConfigResponse) GetRechargeDailyLimit() int64 {
	if x != nil {
		return x.RechargeDailyLimit
	}
	return 0
}

func (x *GetFinanceConfigResponse) GetWithdrawDailyLimit() int64 {
	if x != nil {
		return x.WithdrawDailyLimit
	}
	return 0
}

func (x *GetFinanceConfigResponse) GetWithdrawDailyCount() int32 {
	if x != nil {
		return x.WithdrawDailyCount
	}
	return 0
}

func (x *GetFinanceConfigResponse) GetWithdrawFeeRate() int64 {
	if x != nil {
		return x.WithdrawFeeRate
	}
	return 0
}

// 更新资金配置请求
type UpdateFinanceConfigRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RechargeEnabled    bool                   `protobuf:"varint,1,opt,name=recharge_enabled,json=rechargeEnabled,proto3" json:"recharge_enabled,omitempty"`
	WithdrawEnabled    bool                   `protobuf:"varint,2,opt,name=withdraw_enabled,json=withdrawEnabled,proto3" json:"withdraw_enabled,omitempty"`
	RechargeDailyLimit int64                  `protobuf:"varint,3,opt,name=recharge_daily_limit,json=rechargeDailyLimit,proto3" json:"recharge_daily_limit,omitempty"`
	WithdrawDailyLimit int64                  `protobuf:"varint,4,opt,name=withdraw_daily_limit,json=withdrawDailyLimit,proto3" json:"withdraw_daily_limit,omitempty"`
	WithdrawDailyCount int32                  `protobuf:"varint,5,opt,name=withdraw_daily_count,json=withdrawDailyCount,proto3" json:"withdraw_daily_count,omitempty"`
	WithdrawFeeRate    int64                  `protobuf:"varint,6,opt,name=withdraw_fee_rate,json=withdrawFeeRate,proto3" json:"withdraw_fee_rate,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateFinanceConfigRequest) Reset() {
	*x = UpdateFinanceConfigRequest{}
	mi := &file_admin_finance_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFinanceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFinanceConfigRequest) ProtoMessage() {}

func (x *UpdateFinanceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFinanceConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateFinanceConfigRequest) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateFinanceConfigRequest) GetRechargeEnabled() bool {
	if x != nil {
		return x.RechargeEnabled
	}
	return false
}

func (x *UpdateFinanceConfigRequest) GetWithdrawEnabled() bool {
	if x != nil {
		return x.WithdrawEnabled
	}
	return false
}

func (x *UpdateFinanceConfigRequest) GetRechargeDailyLimit() int64 {
	if x != nil {
		return x.RechargeDailyLimit
	}
	return 0
}

func (x *UpdateFinanceConfigRequest) GetWithdrawDailyLimit() int64 {
	if x != nil {
		return x.WithdrawDailyLimit
	}
	return 0
}

func (x *UpdateFinanceConfigRequest) GetWithdrawDailyCount() int32 {
	if x != nil {
		return x.WithdrawDailyCount
	}
	return 0
}

func (x *UpdateFinanceConfigRequest) GetWithdrawFeeRate() int64 {
	if x != nil {
		return x.WithdrawFeeRate
	}
	return 0
}

// 更新资金配置响应
type UpdateFinanceConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFinanceConfigResponse) Reset() {
	*x = UpdateFinanceConfigResponse{}
	mi := &file_admin_finance_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFinanceConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFinanceConfigResponse) ProtoMessage() {}

func (x *UpdateFinanceConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFinanceConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateFinanceConfigResponse) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFinanceConfigResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateFinanceConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取资金流水请求
type GetFinanceRecordsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: form:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" form:"page"`
	// @inject_tag: form:"page_size"
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" form:"page_size"`
	// @inject_tag: form:"user_id"
	UserId int64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" form:"user_id"`
	// @inject_tag: form:"type"
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty" form:"type"`
	// @inject_tag: form:"start_time"
	StartTime int64 `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty" form:"start_time"`
	// @inject_tag: form:"end_time"
	EndTime       int64 `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty" form:"end_time"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFinanceRecordsRequest) Reset() {
	*x = GetFinanceRecordsRequest{}
	mi := &file_admin_finance_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFinanceRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFinanceRecordsRequest) ProtoMessage() {}

func (x *GetFinanceRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFinanceRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetFinanceRecordsRequest) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{4}
}

func (x *GetFinanceRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFinanceRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetFinanceRecordsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFinanceRecordsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetFinanceRecordsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetFinanceRecordsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 获取资金流水响应
type GetFinanceRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*FinanceRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFinanceRecordsResponse) Reset() {
	*x = GetFinanceRecordsResponse{}
	mi := &file_admin_finance_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFinanceRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFinanceRecordsResponse) ProtoMessage() {}

func (x *GetFinanceRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFinanceRecordsResponse.ProtoReflect.Descriptor instead.
func (*GetFinanceRecordsResponse) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{5}
}

func (x *GetFinanceRecordsResponse) GetRecords() []*FinanceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetFinanceRecordsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 资金流水记录
type FinanceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance       int64                  `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	RelatedId     int64                  `protobuf:"varint,6,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinanceRecord) Reset() {
	*x = FinanceRecord{}
	mi := &file_admin_finance_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinanceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinanceRecord) ProtoMessage() {}

func (x *FinanceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinanceRecord.ProtoReflect.Descriptor instead.
func (*FinanceRecord) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{6}
}

func (x *FinanceRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FinanceRecord) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FinanceRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FinanceRecord) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FinanceRecord) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *FinanceRecord) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *FinanceRecord) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FinanceRecord) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 获取待审核充值请求
type GetPendingRechargesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: form:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" form:"page"`
	// @inject_tag: form:"page_size"
	PageSize      int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" form:"page_size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingRechargesRequest) Reset() {
	*x = GetPendingRechargesRequest{}
	mi := &file_admin_finance_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingRechargesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingRechargesRequest) ProtoMessage() {}

func (x *GetPendingRechargesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingRechargesRequest.ProtoReflect.Descriptor instead.
func (*GetPendingRechargesRequest) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{7}
}

func (x *GetPendingRechargesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPendingRechargesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取待审核充值响应
type GetPendingRechargesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recharges     []*RechargeInfo        `protobuf:"bytes,1,rep,name=recharges,proto3" json:"recharges,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingRechargesResponse) Reset() {
	*x = GetPendingRechargesResponse{}
	mi := &file_admin_finance_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingRechargesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingRechargesResponse) ProtoMessage() {}

func (x *GetPendingRechargesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingRechargesResponse.ProtoReflect.Descriptor instead.
func (*GetPendingRechargesResponse) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{8}
}

func (x *GetPendingRechargesResponse) GetRecharges() []*RechargeInfo {
	if x != nil {
		return x.Recharges
	}
	return nil
}

func (x *GetPendingRechargesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 充值信息
type RechargeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeInfo) Reset() {
	*x = RechargeInfo{}
	mi := &file_admin_finance_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeInfo) ProtoMessage() {}

func (x *RechargeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeInfo.ProtoReflect.Descriptor instead.
func (*RechargeInfo) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{9}
}

func (x *RechargeInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RechargeInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RechargeInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RechargeInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RechargeInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RechargeInfo) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 审核充值请求
type AuditRechargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRechargeRequest) Reset() {
	*x = AuditRechargeRequest{}
	mi := &file_admin_finance_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRechargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRechargeRequest) ProtoMessage() {}

func (x *AuditRechargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRechargeRequest.ProtoReflect.Descriptor instead.
func (*AuditRechargeRequest) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{10}
}

func (x *AuditRechargeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditRechargeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditRechargeRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// 审核充值响应
type AuditRechargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRechargeResponse) Reset() {
	*x = AuditRechargeResponse{}
	mi := &file_admin_finance_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRechargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRechargeResponse) ProtoMessage() {}

func (x *AuditRechargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRechargeResponse.ProtoReflect.Descriptor instead.
func (*AuditRechargeResponse) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{11}
}

func (x *AuditRechargeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuditRechargeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取待审核提现请求
type GetPendingWithdrawsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: form:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" form:"page"`
	// @inject_tag: form:"page_size"
	PageSize      int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" form:"page_size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingWithdrawsRequest) Reset() {
	*x = GetPendingWithdrawsRequest{}
	mi := &file_admin_finance_finance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingWithdrawsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingWithdrawsRequest) ProtoMessage() {}

func (x *GetPendingWithdrawsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingWithdrawsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingWithdrawsRequest) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{12}
}

func (x *GetPendingWithdrawsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPendingWithdrawsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取待审核提现响应
type GetPendingWithdrawsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdraws     []*WithdrawInfo        `protobuf:"bytes,1,rep,name=withdraws,proto3" json:"withdraws,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingWithdrawsResponse) Reset() {
	*x = GetPendingWithdrawsResponse{}
	mi := &file_admin_finance_finance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingWithdrawsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingWithdrawsResponse) ProtoMessage() {}

func (x *GetPendingWithdrawsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingWithdrawsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingWithdrawsResponse) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{13}
}

func (x *GetPendingWithdrawsResponse) GetWithdraws() []*WithdrawInfo {
	if x != nil {
		return x.Withdraws
	}
	return nil
}

func (x *GetPendingWithdrawsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 提现信息
type WithdrawInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee           int64                  `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawInfo) Reset() {
	*x = WithdrawInfo{}
	mi := &file_admin_finance_finance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawInfo) ProtoMessage() {}

func (x *WithdrawInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawInfo.ProtoReflect.Descriptor instead.
func (*WithdrawInfo) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{14}
}

func (x *WithdrawInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WithdrawInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WithdrawInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *WithdrawInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawInfo) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *WithdrawInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WithdrawInfo) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 审核提现请求
type AuditWithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditWithdrawRequest) Reset() {
	*x = AuditWithdrawRequest{}
	mi := &file_admin_finance_finance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditWithdrawRequest) ProtoMessage() {}

func (x *AuditWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditWithdrawRequest.ProtoReflect.Descriptor instead.
func (*AuditWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{15}
}

func (x *AuditWithdrawRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditWithdrawRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditWithdrawRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// 审核提现响应
type AuditWithdrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditWithdrawResponse) Reset() {
	*x = AuditWithdrawResponse{}
	mi := &file_admin_finance_finance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditWithdrawResponse) ProtoMessage() {}

func (x *AuditWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditWithdrawResponse.ProtoReflect.Descriptor instead.
func (*AuditWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{16}
}

func (x *AuditWithdrawResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuditWithdrawResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 调整用户余额请求
type AdjustBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustBalanceRequest) Reset() {
	*x = AdjustBalanceRequest{}
	mi := &file_admin_finance_finance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustBalanceRequest) ProtoMessage() {}

func (x *AdjustBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustBalanceRequest.ProtoReflect.Descriptor instead.
func (*AdjustBalanceRequest) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{17}
}

func (x *AdjustBalanceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdjustBalanceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AdjustBalanceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 调整用户余额响应
type AdjustBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustBalanceResponse) Reset() {
	*x = AdjustBalanceResponse{}
	mi := &file_admin_finance_finance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustBalanceResponse) ProtoMessage() {}

func (x *AdjustBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_finance_finance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustBalanceResponse.ProtoReflect.Descriptor instead.
func (*AdjustBalanceResponse) Descriptor() ([]byte, []int) {
	return file_admin_finance_finance_proto_rawDescGZIP(), []int{18}
}

func (x *AdjustBalanceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdjustBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_admin_finance_finance_proto protoreflect.FileDescriptor

const file_admin_finance_finance_proto_rawDesc = "" +
	"\n" +
	"\x1badmin/finance/finance.proto\x12\radmin_finance\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x19\n" +
	"\x17GetFinanceConfigRequest\"\xb2\x02\n" +
	"\x18GetFinanceConfigResponse\x12)\n" +
	"\x10recharge_enabled\x18\x01 \x01(\bR\x0frechargeEnabled\x12)\n" +
	"\x10withdraw_enabled\x18\x02 \x01(\bR\x0fwithdrawEnabled\x120\n" +
	"\x14recharge_daily_limit\x18\x03 \x01(\x03R\x12rechargeDailyLimit\x120\n" +
	"\x14withdraw_daily_limit\x18\x04 \x01(\x03R\x12withdrawDailyLimit\x120\n" +
	"\x14withdraw_daily_count\x18\x05 \x01(\x05R\x12withdrawDailyCount\x12*\n" +
	"\x11withdraw_fee_rate\x18\x06 \x01(\x03R\x0fwithdrawFeeRate\"\xb4\x02\n" +
	"\x1aUpdateFinanceConfigRequest\x12)\n" +
	"\x10recharge_enabled\x18\x01 \x01(\bR\x0frechargeEnabled\x12)\n" +
	"\x10withdraw_enabled\x18\x02 \x01(\bR\x0fwithdrawEnabled\x120\n" +
	"\x14recharge_daily_limit\x18\x03 \x01(\x03R\x12rechargeDailyLimit\x120\n" +
	"\x14withdraw_daily_limit\x18\x04 \x01(\x03R\x12withdrawDailyLimit\x120\n" +
	"\x14withdraw_daily_count\x18\x05 \x01(\x05R\x12withdrawDailyCount\x12*\n" +
	"\x11withdraw_fee_rate\x18\x06 \x01(\x03R\x0fwithdrawFeeRate\"K\n" +
	"\x1bUpdateFinanceConfigResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb2\x01\n" +
	"\x18GetFinanceRecordsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\"i\n" +
	"\x19GetFinanceRecordsResponse\x126\n" +
	"\arecords\x18\x01 \x03(\v2\x1c.admin_finance.FinanceRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xf0\x01\n" +
	"\rFinanceRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x03R\abalance\x12\x1d\n" +
	"\n" +
	"related_id\x18\x06 \x01(\x03R\trelatedId\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"M\n" +
	"\x1aGetPendingRechargesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"n\n" +
	"\x1bGetPendingRechargesResponse\x129\n" +
	"\trecharges\x18\x01 \x03(\v2\x1b.admin_finance.RechargeInfoR\trecharges\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd7\x01\n" +
	"\fRechargeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"s\n" +
	"\x14AuditRechargeRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12.\n" +
	"\x06action\x18\x02 \x01(\tB\x16\xfaB\x13r\x11R\aapproveR\x06rejectR\x06action\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"E\n" +
	"\x15AuditRechargeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x1aGetPendingWithdrawsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"n\n" +
	"\x1bGetPendingWithdrawsResponse\x129\n" +
	"\twithdraws\x18\x01 \x03(\v2\x1b.admin_finance.WithdrawInfoR\twithdraws\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd1\x01\n" +
	"\fWithdrawInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x03R\x03fee\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"s\n" +
	"\x14AuditWithdrawRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12.\n" +
	"\x06action\x18\x02 \x01(\tB\x16\xfaB\x13r\x11R\aapproveR\x06rejectR\x06action\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"E\n" +
	"\x15AuditWithdrawResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"q\n" +
	"\x14AdjustBalanceRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1f\n" +
	"\x06reason\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06reason\"E\n" +
	"\x15AdjustBalanceResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf2\b\n" +
	"\fAdminFinance\x12\x82\x01\n" +
	"\x10GetFinanceConfig\x12&.admin_finance.GetFinanceConfigRequest\x1a'.admin_finance.GetFinanceConfigResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/admin/finance/config\x12\x8e\x01\n" +
	"\x13UpdateFinanceConfig\x12).admin_finance.UpdateFinanceConfigRequest\x1a*.admin_finance.UpdateFinanceConfigResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/admin/finance/config\x12\x86\x01\n" +
	"\x11GetFinanceRecords\x12'.admin_finance.GetFinanceRecordsRequest\x1a(.admin_finance.GetFinanceRecordsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/admin/finance/records\x12\x95\x01\n" +
	"\x13GetPendingRecharges\x12).admin_finance.GetPendingRechargesRequest\x1a*.admin_finance.GetPendingRechargesResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/admin/finance/recharge/pending\x12\x84\x01\n" +
	"\rAuditRecharge\x12#.admin_finance.AuditRechargeRequest\x1a$.admin_finance.AuditRechargeResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/admin/finance/recharge/audit\x12\x95\x01\n" +
	"\x13GetPendingWithdraws\x12).admin_finance.GetPendingWithdrawsRequest\x1a*.admin_finance.GetPendingWithdrawsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/admin/finance/withdraw/pending\x12\x84\x01\n" +
	"\rAuditWithdraw\x12#.admin_finance.AuditWithdrawRequest\x1a$.admin_finance.AuditWithdrawResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/admin/finance/withdraw/audit\x12\x84\x01\n" +
	"\rAdjustBalance\x12#.admin_finance.AdjustBalanceRequest\x1a$.admin_finance.AdjustBalanceResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/admin/finance/balance/adjustB\x1aZ\x18gochat/api/admin/financeb\x06proto3"

var (
	file_admin_finance_finance_proto_rawDescOnce sync.Once
	file_admin_finance_finance_proto_rawDescData []byte
)

func file_admin_finance_finance_proto_rawDescGZIP() []byte {
	file_admin_finance_finance_proto_rawDescOnce.Do(func() {
		file_admin_finance_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_finance_finance_proto_rawDesc), len(file_admin_finance_finance_proto_rawDesc)))
	})
	return file_admin_finance_finance_proto_rawDescData
}

var file_admin_finance_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_admin_finance_finance_proto_goTypes = []any{
	(*GetFinanceConfigRequest)(nil),     // 0: admin_finance.GetFinanceConfigRequest
	(*GetFinanceConfigResponse)(nil),    // 1: admin_finance.GetFinanceConfigResponse
	(*UpdateFinanceConfigRequest)(nil),  // 2: admin_finance.UpdateFinanceConfigRequest
	(*UpdateFinanceConfigResponse)(nil), // 3: admin_finance.UpdateFinanceConfigResponse
	(*GetFinanceRecordsRequest)(nil),    // 4: admin_finance.GetFinanceRecordsRequest
	(*GetFinanceRecordsResponse)(nil),   // 5: admin_finance.GetFinanceRecordsResponse
	(*FinanceRecord)(nil),               // 6: admin_finance.FinanceRecord
	(*GetPendingRechargesRequest)(nil),  // 7: admin_finance.GetPendingRechargesRequest
	(*GetPendingRechargesResponse)(nil), // 8: admin_finance.GetPendingRechargesResponse
	(*RechargeInfo)(nil),                // 9: admin_finance.RechargeInfo
	(*AuditRechargeRequest)(nil),        // 10: admin_finance.AuditRechargeRequest
	(*AuditRechargeResponse)(nil),       // 11: admin_finance.AuditRechargeResponse
	(*GetPendingWithdrawsRequest)(nil),  // 12: admin_finance.GetPendingWithdrawsRequest
	(*GetPendingWithdrawsResponse)(nil), // 13: admin_finance.GetPendingWithdrawsResponse
	(*WithdrawInfo)(nil),                // 14: admin_finance.WithdrawInfo
	(*AuditWithdrawRequest)(nil),        // 15: admin_finance.AuditWithdrawRequest
	(*AuditWithdrawResponse)(nil),       // 16: admin_finance.AuditWithdrawResponse
	(*AdjustBalanceRequest)(nil),        // 17: admin_finance.AdjustBalanceRequest
	(*AdjustBalanceResponse)(nil),       // 18: admin_finance.AdjustBalanceResponse
	(*timestamp.Timestamp)(nil),         // 19: google.protobuf.Timestamp
}
var file_admin_finance_finance_proto_depIdxs = []int32{
	6,  // 0: admin_finance.GetFinanceRecordsResponse.records:type_name -> admin_finance.FinanceRecord
	19, // 1: admin_finance.FinanceRecord.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: admin_finance.GetPendingRechargesResponse.recharges:type_name -> admin_finance.RechargeInfo
	19, // 3: admin_finance.RechargeInfo.created_at:type_name -> google.protobuf.Timestamp
	14, // 4: admin_finance.GetPendingWithdrawsResponse.withdraws:type_name -> admin_finance.WithdrawInfo
	19, // 5: admin_finance.WithdrawInfo.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: admin_finance.AdminFinance.GetFinanceConfig:input_type -> admin_finance.GetFinanceConfigRequest
	2,  // 7: admin_finance.AdminFinance.UpdateFinanceConfig:input_type -> admin_finance.UpdateFinanceConfigRequest
	4,  // 8: admin_finance.AdminFinance.GetFinanceRecords:input_type -> admin_finance.GetFinanceRecordsRequest
	7,  // 9: admin_finance.AdminFinance.GetPendingRecharges:input_type -> admin_finance.GetPendingRechargesRequest
	10, // 10: admin_finance.AdminFinance.AuditRecharge:input_type -> admin_finance.AuditRechargeRequest
	12, // 11: admin_finance.AdminFinance.GetPendingWithdraws:input_type -> admin_finance.GetPendingWithdrawsRequest
	15, // 12: admin_finance.AdminFinance.AuditWithdraw:input_type -> admin_finance.AuditWithdrawRequest
	17, // 13: admin_finance.AdminFinance.AdjustBalance:input_type -> admin_finance.AdjustBalanceRequest
	1,  // 14: admin_finance.AdminFinance.GetFinanceConfig:output_type -> admin_finance.GetFinanceConfigResponse
	3,  // 15: admin_finance.AdminFinance.UpdateFinanceConfig:output_type -> admin_finance.UpdateFinanceConfigResponse
	5,  // 16: admin_finance.AdminFinance.GetFinanceRecords:output_type -> admin_finance.GetFinanceRecordsResponse
	8,  // 17: admin_finance.AdminFinance.GetPendingRecharges:output_type -> admin_finance.GetPendingRechargesResponse
	11, // 18: admin_finance.AdminFinance.AuditRecharge:output_type -> admin_finance.AuditRechargeResponse
	13, // 19: admin_finance.AdminFinance.GetPendingWithdraws:output_type -> admin_finance.GetPendingWithdrawsResponse
	16, // 20: admin_finance.AdminFinance.AuditWithdraw:output_type -> admin_finance.AuditWithdrawResponse
	18, // 21: admin_finance.AdminFinance.AdjustBalance:output_type -> admin_finance.AdjustBalanceResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_admin_finance_finance_proto_init() }
func file_admin_finance_finance_proto_init() {
	if File_admin_finance_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_finance_finance_proto_rawDesc), len(file_admin_finance_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_finance_finance_proto_goTypes,
		DependencyIndexes: file_admin_finance_finance_proto_depIdxs,
		MessageInfos:      file_admin_finance_finance_proto_msgTypes,
	}.Build()
	File_admin_finance_finance_proto = out.File
	file_admin_finance_finance_proto_goTypes = nil
	file_admin_finance_finance_proto_depIdxs = nil
}
