// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.4
// source: api/notification/notification.proto

package notification

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取通知列表请求
type GetNotificationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: form:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" form:"page"` // 页码
	// @inject_tag: form:"page_size"
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" form:"page_size"` // 每页数量
	// @inject_tag: form:"type"
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty" form:"type"` // 通知类型（可选，为空则查询所有）
	// @inject_tag: form:"is_read"
	IsRead        string `protobuf:"bytes,4,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty" form:"is_read"` // 是否已读（可选，"true"/"false"/""，为空则查询所有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	mi := &file_api_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *GetNotificationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetNotificationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetNotificationsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetNotificationsRequest) GetIsRead() string {
	if x != nil {
		return x.IsRead
	}
	return ""
}

// 获取通知列表响应
type GetNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*NotificationInfo    `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`                 // 通知列表
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`    // 总数量
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"` // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`          // 每页数量
	UnreadCount   int32                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"` // 未读数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsResponse) Reset() {
	*x = GetNotificationsResponse{}
	mi := &file_api_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsResponse) ProtoMessage() {}

func (x *GetNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *GetNotificationsResponse) GetNotifications() []*NotificationInfo {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *GetNotificationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetNotificationsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetNotificationsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetNotificationsResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// 通知信息
type NotificationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // 通知ID
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                             // 通知类型
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                           // 通知标题
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                       // 通知内容
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                        // 金额(单位:分，如果有)
	RelatedId     uint64                 `protobuf:"varint,6,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"` // 关联记录ID
	IsRead        bool                   `protobuf:"varint,7,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`          // 是否已读
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationInfo) Reset() {
	*x = NotificationInfo{}
	mi := &file_api_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationInfo) ProtoMessage() {}

func (x *NotificationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationInfo.ProtoReflect.Descriptor instead.
func (*NotificationInfo) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NotificationInfo) GetRelatedId() uint64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *NotificationInfo) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *NotificationInfo) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 标记通知已读请求
type MarkAsReadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NotificationIds []uint64               `protobuf:"varint,1,rep,packed,name=notification_ids,json=notificationIds,proto3" json:"notification_ids,omitempty"` // 通知ID列表
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_api_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *MarkAsReadRequest) GetNotificationIds() []uint64 {
	if x != nil {
		return x.NotificationIds
	}
	return nil
}

// 标记通知已读响应
type MarkAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                               // 是否成功
	UpdatedCount  int32                  `protobuf:"varint,2,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"` // 更新的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadResponse) Reset() {
	*x = MarkAsReadResponse{}
	mi := &file_api_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadResponse) ProtoMessage() {}

func (x *MarkAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAsReadResponse) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *MarkAsReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MarkAsReadResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

// 标记所有通知已读请求
type MarkAllAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadRequest) Reset() {
	*x = MarkAllAsReadRequest{}
	mi := &file_api_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadRequest) ProtoMessage() {}

func (x *MarkAllAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadRequest) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{5}
}

// 标记所有通知已读响应
type MarkAllAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                               // 是否成功
	UpdatedCount  int32                  `protobuf:"varint,2,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"` // 更新的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadResponse) Reset() {
	*x = MarkAllAsReadResponse{}
	mi := &file_api_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadResponse) ProtoMessage() {}

func (x *MarkAllAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadResponse) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *MarkAllAsReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MarkAllAsReadResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

// 获取未读通知数量请求
type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_api_notification_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{7}
}

// 获取未读通知数量响应
type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 未读数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_api_notification_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{8}
}

func (x *GetUnreadCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 删除通知请求
type DeleteNotificationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NotificationIds []uint64               `protobuf:"varint,1,rep,packed,name=notification_ids,json=notificationIds,proto3" json:"notification_ids,omitempty"` // 通知ID列表
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_api_notification_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNotificationRequest) GetNotificationIds() []uint64 {
	if x != nil {
		return x.NotificationIds
	}
	return nil
}

// 删除通知响应
type DeleteNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                               // 是否成功
	DeletedCount  int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"` // 删除的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationResponse) Reset() {
	*x = DeleteNotificationResponse{}
	mi := &file_api_notification_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationResponse) ProtoMessage() {}

func (x *DeleteNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationResponse.ProtoReflect.Descriptor instead.
func (*DeleteNotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_notification_notification_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteNotificationResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_api_notification_notification_proto protoreflect.FileDescriptor

const file_api_notification_notification_proto_rawDesc = "" +
	"\n" +
	"#api/notification/notification.proto\x12\x10api.notification\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"\x8b\x01\n" +
	"\x17GetNotificationsRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x04page\x12&\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d \x00R\bpageSize\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x17\n" +
	"\ais_read\x18\x04 \x01(\tR\x06isRead\"\xe8\x01\n" +
	"\x18GetNotificationsResponse\x12H\n" +
	"\rnotifications\x18\x01 \x03(\v2\".api.notification.NotificationInfoR\rnotifications\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12!\n" +
	"\funread_count\x18\x05 \x01(\x05R\vunreadCount\"\xf1\x01\n" +
	"\x10NotificationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"related_id\x18\x06 \x01(\x04R\trelatedId\x12\x17\n" +
	"\ais_read\x18\a \x01(\bR\x06isRead\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"H\n" +
	"\x11MarkAsReadRequest\x123\n" +
	"\x10notification_ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x0fnotificationIds\"S\n" +
	"\x12MarkAsReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rupdated_count\x18\x02 \x01(\x05R\fupdatedCount\"\x16\n" +
	"\x14MarkAllAsReadRequest\"V\n" +
	"\x15MarkAllAsReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rupdated_count\x18\x02 \x01(\x05R\fupdatedCount\"\x17\n" +
	"\x15GetUnreadCountRequest\".\n" +
	"\x16GetUnreadCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"P\n" +
	"\x19DeleteNotificationRequest\x123\n" +
	"\x10notification_ids\x18\x01 \x03(\x04B\b\xfaB\x05\x92\x01\x02\b\x01R\x0fnotificationIds\"[\n" +
	"\x1aDeleteNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount2\xcc\x05\n" +
	"\x13NotificationService\x12\x89\x01\n" +
	"\x10GetNotifications\x12).api.notification.GetNotificationsRequest\x1a*.api.notification.GetNotificationsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/notification/list\x12z\n" +
	"\n" +
	"MarkAsRead\x12#.api.notification.MarkAsReadRequest\x1a$.api.notification.MarkAsReadResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/notification/read\x12\x87\x01\n" +
	"\rMarkAllAsRead\x12&.api.notification.MarkAllAsReadRequest\x1a'.api.notification.MarkAllAsReadResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/notification/read-all\x12\x8b\x01\n" +
	"\x0eGetUnreadCount\x12'.api.notification.GetUnreadCountRequest\x1a(.api.notification.GetUnreadCountResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/notification/unread-count\x12\x94\x01\n" +
	"\x12DeleteNotification\x12+.api.notification.DeleteNotificationRequest\x1a,.api.notification.DeleteNotificationResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/notification/deleteB\x1dZ\x1bgochat/api/api/notificationb\x06proto3"

var (
	file_api_notification_notification_proto_rawDescOnce sync.Once
	file_api_notification_notification_proto_rawDescData []byte
)

func file_api_notification_notification_proto_rawDescGZIP() []byte {
	file_api_notification_notification_proto_rawDescOnce.Do(func() {
		file_api_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notification_notification_proto_rawDesc), len(file_api_notification_notification_proto_rawDesc)))
	})
	return file_api_notification_notification_proto_rawDescData
}

var file_api_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_notification_notification_proto_goTypes = []any{
	(*GetNotificationsRequest)(nil),    // 0: api.notification.GetNotificationsRequest
	(*GetNotificationsResponse)(nil),   // 1: api.notification.GetNotificationsResponse
	(*NotificationInfo)(nil),           // 2: api.notification.NotificationInfo
	(*MarkAsReadRequest)(nil),          // 3: api.notification.MarkAsReadRequest
	(*MarkAsReadResponse)(nil),         // 4: api.notification.MarkAsReadResponse
	(*MarkAllAsReadRequest)(nil),       // 5: api.notification.MarkAllAsReadRequest
	(*MarkAllAsReadResponse)(nil),      // 6: api.notification.MarkAllAsReadResponse
	(*GetUnreadCountRequest)(nil),      // 7: api.notification.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),     // 8: api.notification.GetUnreadCountResponse
	(*DeleteNotificationRequest)(nil),  // 9: api.notification.DeleteNotificationRequest
	(*DeleteNotificationResponse)(nil), // 10: api.notification.DeleteNotificationResponse
	(*timestamp.Timestamp)(nil),        // 11: google.protobuf.Timestamp
}
var file_api_notification_notification_proto_depIdxs = []int32{
	2,  // 0: api.notification.GetNotificationsResponse.notifications:type_name -> api.notification.NotificationInfo
	11, // 1: api.notification.NotificationInfo.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: api.notification.NotificationService.GetNotifications:input_type -> api.notification.GetNotificationsRequest
	3,  // 3: api.notification.NotificationService.MarkAsRead:input_type -> api.notification.MarkAsReadRequest
	5,  // 4: api.notification.NotificationService.MarkAllAsRead:input_type -> api.notification.MarkAllAsReadRequest
	7,  // 5: api.notification.NotificationService.GetUnreadCount:input_type -> api.notification.GetUnreadCountRequest
	9,  // 6: api.notification.NotificationService.DeleteNotification:input_type -> api.notification.DeleteNotificationRequest
	1,  // 7: api.notification.NotificationService.GetNotifications:output_type -> api.notification.GetNotificationsResponse
	4,  // 8: api.notification.NotificationService.MarkAsRead:output_type -> api.notification.MarkAsReadResponse
	6,  // 9: api.notification.NotificationService.MarkAllAsRead:output_type -> api.notification.MarkAllAsReadResponse
	8,  // 10: api.notification.NotificationService.GetUnreadCount:output_type -> api.notification.GetUnreadCountResponse
	10, // 11: api.notification.NotificationService.DeleteNotification:output_type -> api.notification.DeleteNotificationResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_notification_notification_proto_init() }
func file_api_notification_notification_proto_init() {
	if File_api_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notification_notification_proto_rawDesc), len(file_api_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notification_notification_proto_goTypes,
		DependencyIndexes: file_api_notification_notification_proto_depIdxs,
		MessageInfos:      file_api_notification_notification_proto_msgTypes,
	}.Build()
	File_api_notification_notification_proto = out.File
	file_api_notification_notification_proto_goTypes = nil
	file_api_notification_notification_proto_depIdxs = nil
}
