// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: admin/log/log.proto

package log

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminLog_GetLogs_FullMethodName = "/admin_log.AdminLog/GetLogs"
)

// AdminLogClient is the client API for AdminLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 操作日志服务
type AdminLogClient interface {
	// 获取操作日志
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
}

type adminLogClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminLogClient(cc grpc.ClientConnInterface) AdminLogClient {
	return &adminLogClient{cc}
}

func (c *adminLogClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogsResponse)
	err := c.cc.Invoke(ctx, AdminLog_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminLogServer is the server API for AdminLog service.
// All implementations must embed UnimplementedAdminLogServer
// for forward compatibility.
//
// 操作日志服务
type AdminLogServer interface {
	// 获取操作日志
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error)
	mustEmbedUnimplementedAdminLogServer()
}

// UnimplementedAdminLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminLogServer struct{}

func (UnimplementedAdminLogServer) GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedAdminLogServer) mustEmbedUnimplementedAdminLogServer() {}
func (UnimplementedAdminLogServer) testEmbeddedByValue()                  {}

// UnsafeAdminLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminLogServer will
// result in compilation errors.
type UnsafeAdminLogServer interface {
	mustEmbedUnimplementedAdminLogServer()
}

func RegisterAdminLogServer(s grpc.ServiceRegistrar, srv AdminLogServer) {
	// If the following call panics, it indicates UnimplementedAdminLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminLog_ServiceDesc, srv)
}

func _AdminLog_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminLogServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminLog_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminLogServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminLog_ServiceDesc is the grpc.ServiceDesc for AdminLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_log.AdminLog",
	HandlerType: (*AdminLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLogs",
			Handler:    _AdminLog_GetLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/log/log.proto",
}
