definitions:
  models.UserBasic:
    type: object
info:
  contact: {}
paths:
  /user/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserBasic'
      produces:
      - application/json
      responses:
        "200":
          description: code","data","message"}
          schema:
            type: string
      tags:
      - 创建用户
  /user/list:
    get:
      responses:
        "200":
          description: code","data"}
          schema:
            type: string
      tags:
      - 测试用户列表
swagger: "2.0"
