// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/call/call.proto

package call

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallService_StartPrivateCall_FullMethodName = "/api.call.CallService/StartPrivateCall"
	CallService_StartGroupCall_FullMethodName   = "/api.call.CallService/StartGroupCall"
	CallService_AcceptCall_FullMethodName       = "/api.call.CallService/AcceptCall"
	CallService_RejectCall_FullMethodName       = "/api.call.CallService/RejectCall"
	CallService_CancelCall_FullMethodName       = "/api.call.CallService/CancelCall"
	CallService_EndCall_FullMethodName          = "/api.call.CallService/EndCall"
	CallService_GetCallRecords_FullMethodName   = "/api.call.CallService/GetCallRecords"
)

// CallServiceClient is the client API for CallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 通话服务
type CallServiceClient interface {
	// 发起私聊通话
	StartPrivateCall(ctx context.Context, in *StartPrivateCallRequest, opts ...grpc.CallOption) (*StartPrivateCallResponse, error)
	// 发起群聊通话
	StartGroupCall(ctx context.Context, in *StartGroupCallRequest, opts ...grpc.CallOption) (*StartGroupCallResponse, error)
	// 接受通话
	AcceptCall(ctx context.Context, in *AcceptCallRequest, opts ...grpc.CallOption) (*AcceptCallResponse, error)
	// 拒绝通话
	RejectCall(ctx context.Context, in *RejectCallRequest, opts ...grpc.CallOption) (*RejectCallResponse, error)
	// 取消通话（发起者取消）
	CancelCall(ctx context.Context, in *CancelCallRequest, opts ...grpc.CallOption) (*CancelCallResponse, error)
	// 结束通话
	EndCall(ctx context.Context, in *EndCallRequest, opts ...grpc.CallOption) (*EndCallResponse, error)
	// 获取通话记录
	GetCallRecords(ctx context.Context, in *GetCallRecordsRequest, opts ...grpc.CallOption) (*GetCallRecordsResponse, error)
}

type callServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallServiceClient(cc grpc.ClientConnInterface) CallServiceClient {
	return &callServiceClient{cc}
}

func (c *callServiceClient) StartPrivateCall(ctx context.Context, in *StartPrivateCallRequest, opts ...grpc.CallOption) (*StartPrivateCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartPrivateCallResponse)
	err := c.cc.Invoke(ctx, CallService_StartPrivateCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) StartGroupCall(ctx context.Context, in *StartGroupCallRequest, opts ...grpc.CallOption) (*StartGroupCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGroupCallResponse)
	err := c.cc.Invoke(ctx, CallService_StartGroupCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) AcceptCall(ctx context.Context, in *AcceptCallRequest, opts ...grpc.CallOption) (*AcceptCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptCallResponse)
	err := c.cc.Invoke(ctx, CallService_AcceptCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) RejectCall(ctx context.Context, in *RejectCallRequest, opts ...grpc.CallOption) (*RejectCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectCallResponse)
	err := c.cc.Invoke(ctx, CallService_RejectCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) CancelCall(ctx context.Context, in *CancelCallRequest, opts ...grpc.CallOption) (*CancelCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelCallResponse)
	err := c.cc.Invoke(ctx, CallService_CancelCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) EndCall(ctx context.Context, in *EndCallRequest, opts ...grpc.CallOption) (*EndCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndCallResponse)
	err := c.cc.Invoke(ctx, CallService_EndCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) GetCallRecords(ctx context.Context, in *GetCallRecordsRequest, opts ...grpc.CallOption) (*GetCallRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCallRecordsResponse)
	err := c.cc.Invoke(ctx, CallService_GetCallRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallServiceServer is the server API for CallService service.
// All implementations must embed UnimplementedCallServiceServer
// for forward compatibility.
//
// 通话服务
type CallServiceServer interface {
	// 发起私聊通话
	StartPrivateCall(context.Context, *StartPrivateCallRequest) (*StartPrivateCallResponse, error)
	// 发起群聊通话
	StartGroupCall(context.Context, *StartGroupCallRequest) (*StartGroupCallResponse, error)
	// 接受通话
	AcceptCall(context.Context, *AcceptCallRequest) (*AcceptCallResponse, error)
	// 拒绝通话
	RejectCall(context.Context, *RejectCallRequest) (*RejectCallResponse, error)
	// 取消通话（发起者取消）
	CancelCall(context.Context, *CancelCallRequest) (*CancelCallResponse, error)
	// 结束通话
	EndCall(context.Context, *EndCallRequest) (*EndCallResponse, error)
	// 获取通话记录
	GetCallRecords(context.Context, *GetCallRecordsRequest) (*GetCallRecordsResponse, error)
	mustEmbedUnimplementedCallServiceServer()
}

// UnimplementedCallServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallServiceServer struct{}

func (UnimplementedCallServiceServer) StartPrivateCall(context.Context, *StartPrivateCallRequest) (*StartPrivateCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPrivateCall not implemented")
}
func (UnimplementedCallServiceServer) StartGroupCall(context.Context, *StartGroupCallRequest) (*StartGroupCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGroupCall not implemented")
}
func (UnimplementedCallServiceServer) AcceptCall(context.Context, *AcceptCallRequest) (*AcceptCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptCall not implemented")
}
func (UnimplementedCallServiceServer) RejectCall(context.Context, *RejectCallRequest) (*RejectCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectCall not implemented")
}
func (UnimplementedCallServiceServer) CancelCall(context.Context, *CancelCallRequest) (*CancelCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCall not implemented")
}
func (UnimplementedCallServiceServer) EndCall(context.Context, *EndCallRequest) (*EndCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndCall not implemented")
}
func (UnimplementedCallServiceServer) GetCallRecords(context.Context, *GetCallRecordsRequest) (*GetCallRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCallRecords not implemented")
}
func (UnimplementedCallServiceServer) mustEmbedUnimplementedCallServiceServer() {}
func (UnimplementedCallServiceServer) testEmbeddedByValue()                     {}

// UnsafeCallServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallServiceServer will
// result in compilation errors.
type UnsafeCallServiceServer interface {
	mustEmbedUnimplementedCallServiceServer()
}

func RegisterCallServiceServer(s grpc.ServiceRegistrar, srv CallServiceServer) {
	// If the following call pancis, it indicates UnimplementedCallServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallService_ServiceDesc, srv)
}

func _CallService_StartPrivateCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPrivateCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).StartPrivateCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_StartPrivateCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).StartPrivateCall(ctx, req.(*StartPrivateCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_StartGroupCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGroupCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).StartGroupCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_StartGroupCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).StartGroupCall(ctx, req.(*StartGroupCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_AcceptCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).AcceptCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_AcceptCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).AcceptCall(ctx, req.(*AcceptCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_RejectCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).RejectCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_RejectCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).RejectCall(ctx, req.(*RejectCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_CancelCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).CancelCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_CancelCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).CancelCall(ctx, req.(*CancelCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_EndCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).EndCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_EndCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).EndCall(ctx, req.(*EndCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_GetCallRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCallRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).GetCallRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_GetCallRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).GetCallRecords(ctx, req.(*GetCallRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CallService_ServiceDesc is the grpc.ServiceDesc for CallService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.call.CallService",
	HandlerType: (*CallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartPrivateCall",
			Handler:    _CallService_StartPrivateCall_Handler,
		},
		{
			MethodName: "StartGroupCall",
			Handler:    _CallService_StartGroupCall_Handler,
		},
		{
			MethodName: "AcceptCall",
			Handler:    _CallService_AcceptCall_Handler,
		},
		{
			MethodName: "RejectCall",
			Handler:    _CallService_RejectCall_Handler,
		},
		{
			MethodName: "CancelCall",
			Handler:    _CallService_CancelCall_Handler,
		},
		{
			MethodName: "EndCall",
			Handler:    _CallService_EndCall_Handler,
		},
		{
			MethodName: "GetCallRecords",
			Handler:    _CallService_GetCallRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/call/call.proto",
}
